name: locadesertahex
description: Loca Deserta Hex Puzzle Game.
publish_to: 'none'
version: 1.0.6+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  simple_animations: ^2.4.2
  soundpool: ^1.1.3
  shared_preferences: ^0.5.11
  rxdart: 0.24.1
  tuple: ^1.0.3
  supercharged: ^1.12.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^1.1.2
  soundpool_macos: ^0.2.7
  url_launcher: ^5.7.10
  bot_toast: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/resources/
    - images/background/
    - images/buildings/
    - assets/sounds/
    - google_fonts/
    - images/other/
    - images/thumbnails/
