name: locadesertahex
description: Loca Deserta Hex Puzzle Game.
publish_to: 'none'
version: 1.0.6+8

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  simple_animations: ^3.1.1
  soundpool: ^2.1.0
  shared_preferences: ^2.0.7
  rxdart: ^0.27.1
  tuple: ^2.0.0
  supercharged: ^2.0.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.1.0
  soundpool_macos: ^2.1.0
  url_launcher: ^6.0.9
  bot_toast: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/resources/
    - images/background/
    - images/buildings/
    - assets/sounds/
    - google_fonts/
    - images/other/
    - images/thumbnails/
